### ISSUE TITLE
Recommend alternative ways of transmitting for Wifi-Password-Grabber

### ISSUE THREAD

**Issue by LavaTiger99** [axel05869/Wifi-Grab#1]
Would like to see a way of sending without gmail, as some business block access to private emails at work.
Maybe uploading (scp/ftp/etc...) to a server, or to be really stealthy embedding the data in a GET or PUT request to a webserver you monitor.

**Comment by axel05869** [comment]
Yeah, you can actually use http://requestbin.net to that. you can explore it yourself on how to implement it as I'm currently busy on my new project. if I have time I can update it in the future.

**Comment by LavaTiger99** [comment]
Very cool site, I will be using that a lot now that I know it exists. I will look into and alternative script as well when I have time.
